/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(GWinApplet appc, GWinData data) { //_CODE_:window1:923271:
  if (isInitialized == false){
    PImage heartPicture = loadImage("Data/Heart1_Normal.png");
    appc.image(heartPicture, 0, 0);
    isInitialized = true;
  }
    PImage heartPicture = loadImage("Data/Heart1_Normal.png");
    if (heartRate >= 127 && heartRate <= 147){
    heartPicture = loadImage("Data/Heart1_Normal.png");
    appc.image(heartPicture, 0, 0);
  }
  if ((heartRate >= 100 && heartRate <= 126) || (heartRate >= 147 && heartRate <= 170)){  
    heartPicture = loadImage("Data/Heart1_Med.png");
    appc.image(heartPicture, 0, 0);
  }
  if ((heartRate < 100 || heartRate >= 170)){
    heartPicture = loadImage("Data/Heart1_Danger.png");
    appc.image(heartPicture, 0, 0);
  }
} //_CODE_:window1:923271:

synchronized public void heartBeat(GWinApplet appc, GWinData data, MouseEvent mevent) { //_CODE_:window1:627846:
  clickCap = false;
  if(appc.mousePressed){
      if (heartRate >= 127 && heartRate <= 147){
        if (clickCap == false){
          for (int forLooper = 0; forLooper < heartHealthy.length; forLooper++){
            PImage heartPicture = loadImage(lazy + heartHealthy[forLooper]);
            appc.image(heartPicture,0,0);
            clickCap = true;
          }
        
          for (int forLooper = 0; forLooper == (flippedHeartHealthy).length; forLooper++){
            PImage heartPicture = loadImage(lazy + (flippedHeartHealthy)[forLooper]);
            appc.image(heartPicture,0,0);
            clickCap = true;
          }
        }
      }
      
      
      if ((heartRate >= 100 && heartRate <= 126) || (heartRate >= 147 && heartRate <= 170)){
        if(clickCap == false){
          for (int forLooper = 0; forLooper < heartMed.length; forLooper++){
            PImage heartPicture = loadImage(lazy + heartMed[forLooper]);
            appc.image(heartPicture,0,0);
            clickCap = true;
          }
          
          for (int forLooper = 0; forLooper == (flippedHeartMed).length; forLooper++){
            PImage heartPicture = loadImage(lazy + (flippedHeartMed)[forLooper]);
            appc.image(heartPicture,0,0);
            clickCap = true;
          }
        }
      }
      
      if ((heartRate < 100 || heartRate >= 170)){
        print("Poeqn");
        if(clickCap == false){
          for (int forLooper = 0; forLooper < heartDanger.length; forLooper++){
            PImage heartPicture = loadImage(lazy + heartDanger[forLooper]);
            appc.image(heartPicture,0,0);
            clickCap = true;
          }
          for (int forLooper = 0; forLooper == (flippedHeartDanger).length; forLooper++){
            PImage heartPicture = loadImage(lazy + flippedHeartDanger[forLooper]);
            appc.image(heartPicture,0,0);
            clickCap = true;
          }
        }
      }
  }
}
  //_CODE_:window1:627846:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  window1 = new GWindow(this, "Heart", 0, 0, 640, 400, false, JAVA2D);
  window1.addDrawHandler(this, "win_draw1");
  window1.addMouseHandler(this, "heartBeat");
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;

