/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw5(GWinApplet appc, GWinData data) { //_CODE_:window1:297475:
int[] a = {3,2,1,0,-1,-2,-3};
int b = 0;
boolean PlusOrMinus = true;


PImage img2 = loadImage("poopitre.png");
appc.image(img2, (a[b] * 640), 0);
if (PlusOrMinus == true){
  b++;
}
else{
  b--;
}
if (b > 6){
  PlusOrMinus = false;
  y = y - 2;
}
if (b < 1){
  PlusOrMinus = true;
  b = b + 2;
}
 print("b = " + b + "\n ");
 print("THE OTHER SHIT = " + a[b] + "\n ");
} //_CODE_:window1:297475:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("PENIS");
  window1 = new GWindow(this, "MEGAPENIS", 0, 0, 640, 400, false, JAVA2D);
  window1.setActionOnClose(G4P.EXIT_APP);
  window1.addDrawHandler(this, "win_draw5");
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;

